spring.datasource.url=jdbc:h2:mem:dematexdb
spring.h2.console.enabled=true
server.compression.enabled=true
logging.level.org.springframework.web=INFO

storage.root=./regulatory_files

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
